// See https://aka.ms/new-console-template for more information
using Adi.Models;

Console.WriteLine("Hello, World!");
Random random = new Random();
var MaxFloor = random.Next(5, 20);
Lift lift = new Lift(MaxFloor);
Building bld = new Building(lift, MaxFloor);
bld.Move();
bld.Move();
bld.Move();
bld.Move();
bld.Move();
bld.Move();
bld.Move();
bld.Move();
bld.Move();
bld.Move();
bld.Move();
bld.Move();
bld.Move();
bld.Move();
bld.Move();
bld.Move();
bld.Move();
bld.Move();
bld.Move();
bld.Move();
bld.Move();
bld.Move();
bld.Move();
bld.Move();
bld.Move();
bld.Move();
bld.Move();
